### ISSUE TITLE
Add map coordinates for consulates

### ISSUE THREAD

**Issue by overeha** [code4romania/Alt-TaskBucket#2]
We need all the lat/long coordinates for the table below:
Add two new columns and fill in for all missions
This is a collaborative document - please be careful with the data and other people working on it. 

https://drive.google.com/file/d/1Gjmgo2qoh1qEavgl2Muv1k2NJ08IjFij/view?usp=sharing

**Comment by GabrielSandor** [comment]
Hello @overeha. I could help with this. May I know which code4ro project this data will be useful for?

**Comment by tudoramariei** [comment]
Hey, @GabrielSandor!  I'm no Olivia but I think this data will be used for [Diaspora Hub](https://code4.ro/ro/apps/diaspora-hub/)
If you still want to help with the task I'll assign it to you
Many thanks! 😄

**Comment by GabrielSandor** [comment]
@tudoramariei sure, i'll gladly do it.

**Comment by GabrielSandor** [comment]
@overeha, @tudoramariei since this data is going to be imported in an application, i assume you need it in decimal (e.g. 24.458537) and not in degrees (e.g. 24°27'30.7"N).

**Comment by tudoramariei** [comment]
Yes! Decimal is the way to go here

**Comment by GabrielSandor** [comment]
@tudoramariei, @overeha i managed to fill in all coordinates except for 2 locations - Kabul and Podgorica. The former is decommissioned after a terrorist attack in 2019, while for the later i could not pinpoint a location inside the city, the address is not clear enough apparently.

**Comment by tudoramariei** [comment]
Thanks, @GabrielSandor! I think this should be good.
I'll take a look over the Podgorica case and check if there's any relevant information.
Great job! 🙌
