### ISSUE TITLE
Clean-up phone numbers in table

### ISSUE THREAD

**Issue by overeha** [code4romania/Alt-TaskBucket#3]
We need 

- all the phone number to use the same format with ”00” in front of the country code, not +. Please clean up and format all hone numbers. 

This is a collaborative document - please be careful with the data and other people working on it. 

https://drive.google.com/file/d/1Gjmgo2qoh1qEavgl2Muv1k2NJ08IjFij/view?usp=sharing

**Comment by alexandrutabolcea** [comment]
ma ocup eu

**Comment by alexandrutabolcea** [comment]
daca va mai fi nevoie si pe viitor, o formula destul de dummy pentru o normalizare a numerelor de telefon:

=SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(G2, "-", ""), "/", CHAR(10)), ", ", CHAR(10)), ")", ""), "(", ""), ".",""), ",",""), " ", ""),"+","00")

**Comment by tudoramariei** [comment]
Fantastic! Thanks a lot @alexandrutabolcea 
Closing this now
