### ISSUE TITLE
Create json for add-on terms dictionary

### ISSUE THREAD

**Issue by overeha** [code4romania/Alt-TaskBucket#4]
We have an add-on that needs to identify terms and expressions related to coronavirus and display an infobox with official news. 

Please take the terms in this excel file and configure them in a json. 
https://docs.google.com/spreadsheets/d/13hIjcFFJoPNq0X9ijU0oNaszstS2ZXz45gS7GHcwVRU/edit?usp=sharing

This task is related to this task, where you can find the json sample file: https://github.com/code4romania/emergency-news-addon/issues/1

**Comment by iFlex** [comment]
Happy to pick this up

**Comment by iFlex** [comment]
Where do I deliver the file once it's done? 
This seems to be the project that needs it but I don't have access to it:
https://github.com/code4romania/emergency-news-addon/blob/master/terms.json

I'll add as many terms related to corona as i can think of. I already have draft file - can that go into the repo already and get incrementally changed?

**Comment by RaduCStefanescu** [comment]
Hi @iFlex 
Would you be able to make a PR for this issue?
Our contributing guide can be found here: https://github.com/code4romania/emergency-news-addon/blob/master/.github/WORKFLOW.md

**Comment by iFlex** [comment]
Hi @RaduCStefanescu - yep will do

**Comment by iFlex** [comment]
@RaduCStefanescu - could you please grant me access to publish my branch so that I can open a pull request?

**Comment by tudoramariei** [comment]
Hey, @iFlex. Our workflow is generally to 
1. fork the upstream repository in our own
2. create a branch for a specific feature
3. make a PR from our branch to the upstream repo

Sorry for not specifically mentioning this earlier

**Comment by iFlex** [comment]
@tudoramariei mersi - the ball is rolling now :)

**Comment by tudoramariei** [comment]
Saw the PR and also left some comments.
Besides what I said, some more changes should be done (e.g. remove keywords like "diaspora", "ce ma fac in diaspora" etc.)
We don't have contextual highlighting implemented yet, so until then we can't properly treat this situations without causing excessive spam.

**Comment by iFlex** [comment]
@tudoramariei - so should this issue close considering what the below thread concluded? or what's next?
https://github.com/code4romania/emergency-news-addon/issues/35

**Comment by tudoramariei** [comment]
Went off my radar for a while. Closing this now.
Thanks a lot @iFlex! 🙌
