### ISSUE TITLE
[Translation] Need translation for pages

### ISSUE THREAD

**Issue by overeha** [code4romania/Alt-TaskBucket#5]
Wee need the english version for the texts present in the CoVid apps pages. 
Can be found here: https://code4.ro/ro/apps/
Document for translation is here: https://docs.google.com/document/d/1N-jJJ8Z4c2kgvxnIIkJTIJSM2dmrgCK2Z4PUAwf5Z64/edit?usp=sharing

**Comment by Utwo** [comment]
Someone from Slack started this yesterday.
[https://docs.google.com/spreadsheets/d/1EALff05Z5lCPbNbvU0TPQ8phottf0F6Ck_rWJAB1w8k/edit#gid=1166435663](https://docs.google.com/spreadsheets/d/1EALff05Z5lCPbNbvU0TPQ8phottf0F6Ck_rWJAB1w8k/edit#gid=1166435663)

Maybe we can merge them.

**Comment by catileptic** [comment]
I have published the ecosystem in both Romanian an English from the get-go. Closing this Issue.
