### ISSUE TITLE
[Design] Create favicons for all CoVid projects

### ISSUE THREAD

**Issue by overeha** [code4romania/Alt-TaskBucket#8]
Need favicons for all projects
Please add favicons here: 
https://drive.google.com/open?id=1zEUdo7jZ2fVKmZyds3ClZwp6bNGYVaXu

![COVID (9)](https://user-images.githubusercontent.com/45068169/76700506-f34ec080-66c0-11ea-980c-84847432388f.png)
![COVID (10)](https://user-images.githubusercontent.com/45068169/76700507-f34ec080-66c0-11ea-9a27-5979136ac331.png)
![COVID (2)](https://user-images.githubusercontent.com/45068169/76700508-f3e75700-66c0-11ea-8c6b-54dc1c3450f3.png)
![COVID (4)](https://user-images.githubusercontent.com/45068169/76700509-f3e75700-66c0-11ea-943a-2f6f46e5bc5a.png)
![COVID](https://user-images.githubusercontent.com/45068169/76700510-f47fed80-66c0-11ea-9a9a-25a90538bf83.png)
![COVID (1)](https://user-images.githubusercontent.com/45068169/76700511-f47fed80-66c0-11ea-827c-94ab0b608019.png)
![COVID (3)](https://user-images.githubusercontent.com/45068169/76700512-f47fed80-66c0-11ea-986a-c1769bc88d72.png)

![COVID (7)](https://user-images.githubusercontent.com/45068169/76700502-f21d9380-66c0-11ea-93b3-5b4c8acb6846.png)
![COVID (6)](https://user-images.githubusercontent.com/45068169/76700503-f2b62a00-66c0-11ea-9740-c8a27f43709f.png)
![Code4Ro-Taskforce](https://user-images.githubusercontent.com/45068169/76700505-f2b62a00-66c0-11ea-978f-de4110c3dd51.png)

**Comment by ionmosincat** [comment]
Do you think the favicons should contain something else except the round icon? Maybe a representative letter inside it?

**Comment by tudoramariei** [comment]
While there's room for improvement, slight adjustments to the current logos won't make a big difference. 
So right now, the best path is to just work with these logos and have them delivered quickly.

Sorry for the wait, @ionmosincat; also, please let me know here if you'd want to take this issue 😄

**Comment by ionmosincat** [comment]
@tudoramariei : I'm not a designer, that's why I wouldn't take the issue if any changes to the logos are needed :)
Otherwise, if making favicons from the round shapes suffices, then please assign me to it, I can deliver them later today (I apologize if I am not very clear)

**Comment by RaduCStefanescu** [comment]
@ionmosincat yes, I think we can work with the favicons as the round shapes, I assigned you to the issue.

**Comment by ionmosincat** [comment]
@tudoramariei, @RaduCStefanescu, @overeha:
I added two versions of favicons, a simple one with no text (simple round shapes) and one with text; you can choose whichever you like more/looks better.

If anything needs changes, please let me know.

**Comment by tudoramariei** [comment]
Just one question, @ionmosincat 
I saw that the `apple-touch-icon.png` from both folders for `task-force` has a white background; **is it a bug or a feature**?
Went through all the favicons and that was the only odd one I could find 🤔

**Comment by ionmosincat** [comment]
@tudoramariei, it was supposed to be a feature :)
The website I created it with showed how both versions looked, and this one seemed better to me. However, I forgot to upload the other one. I did it now, so you can use whichever fits better (_apple-touch-icon.png_ or _apple-touch-icon-white-bg.png_)

**Comment by tudoramariei** [comment]
Closing this thanks to @ionmosincat 🙌
